### ISSUE TITLE
Layout problem in Portrait mode

### ISSUE THREAD

**Issue by evoc** [CodeNKasch/TPHeaven#1]
Input fields are cut off in portrait mode. When turned to landscape it is correct.

Phone: Huawei P20 Pro

![Screenshot_20190410_083227_local dotprint tpheaven](https://user-images.githubusercontent.com/2754431/55856977-38db4300-5b6c-11e9-950b-c0174748db1e.jpg)

PS: When switching between apps the input (of the email address) that was done already gets deleted.

**Comment by CodeNKasch** [comment]
fixed with the upcoming  release.
